<a href="https://colab.research.google.com/github/Heity94/TWSM_Lab/blob/main/Homework/3_Exercise_Representation_1/NL_3_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [223]:
import pickle
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import Binarizer
from gensim.corpora import Dictionary
from gensim.models import TfidfModel

In [224]:
with open ('/content/drive/MyDrive/Colab/data_stemmed.pkl','rb') as handle:
  data_stemmed = pickle.load(handle)

In [225]:
data_stemmed[0]

'car wonder enlighten car saw dai door sport car look late earli call bricklin door small addit bumper separ rest bodi know tellm model engin spec year product car histori info funki look car mail thank brought neighborhood lerxst'

**Bag-of-words (sklearn)**

---



In [226]:
#absolute frequency
vec_abs = CountVectorizer(max_df=0.95, min_df=0.05)
#relative frequency
vec_rel = TfidfVectorizer(max_df=0.95, min_df=0.05,use_idf=False, norm='l1')
#tf-idf frequency
vec_tf = TfidfVectorizer(max_df=0.95, min_df=0.05, smooth_idf=False)

Absolute frequency:


*   Pros: considers word importance, interpretable
*   Cons: not comparable between documents (i.e. long vs. short ones)

Relative frequency:


*   Pros: considers document length, interpretable
*   Cons: common words among all documents are overweighed (e.g. ‘annual’
in annual reports)

TF-idf:


*   Pros: Considers the occurrence among all documents (important for classification)
*   Cons: Difficult interpretation






In [227]:
#transform
corpus_abs = vec_abs.fit_transform(data_stemmed)
corpus_rel = vec_rel.fit_transform(data_stemmed)
corpus_tf = vec_tf.fit_transform(data_stemmed)
print("Absolute frequency: \n",corpus_abs.toarray()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
print("\n")
print("Relative frequency: \n", corpus_rel.toarray())
print("\n")
print("Tf-idf: \n", corpus_tf.toarray())

Absolute frequency: 
 [[0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Relative frequency: 
 [[0.         0.         0.         ... 0.         0.         0.05882353]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.01666667 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


Tf-idf: 
 [[0.         0.         0.         ... 0.         0.         0.12166272]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.11514646 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.    

In [228]:
corpus_abs.toarray().shape

(11314, 246)

In [229]:
#get feature names of tf-idf
print(len(vec_tf.get_feature_names_out()))
print((vec_tf.get_feature_names_out()))

246
['abl' 'accept' 'access' 'actual' 'address' 'advanc' 'ago' 'agre' 'allow'
 'american' 'answer' 'anybodi' 'appreci' 'apr' 'area' 'articl' 'ask'
 'assum' 'avail' 'awai' 'bad' 'base' 'believ' 'best' 'better' 'big' 'bit'
 'book' 'bui' 'call' 'car' 'card' 'care' 'case' 'caus' 'chang' 'check'
 'chip' 'christian' 'claim' 'close' 'com' 'come' 'complet' 'consid'
 'control' 'correct' 'cost' 'cours' 'creat' 'current' 'dai' 'data' 'david'
 'deal' 'design' 'differ' 'discuss' 'drive' 'edu' 'effect' 'email' 'end'
 'engin' 'exampl' 'exist' 'expect' 'experi' 'fact' 'far' 'fax' 'feel'
 'file' 'final' 'follow' 'forc' 'free' 'friend' 'game' 'gener' 'get'
 'given' 'go' 'god' 'good' 'got' 'govern' 'great' 'group' 'guess' 'gui'
 'hand' 'happen' 'hard' 'have' 'heard' 'help' 'high' 'home' 'hope' 'host'
 'human' 'idea' 'import' 'includ' 'info' 'inform' 'interest' 'internet'
 'isn' 'issu' 'john' 'kei' 'kill' 'kind' 'know' 'larg' 'law' 'left' 'let'
 'life' 'like' 'line' 'list' 'littl' 'live' 'local' 'long' 'l

In [230]:
#get feature names of accurate and relative frequency
print(len(vec_abs.get_feature_names_out()))
print(len(vec_rel.get_feature_names_out()))

246
246


In [231]:
#check the difference between the feature names of absolute frequency and tf-idf
print(set(vec_abs.get_feature_names_out())- set(vec_tf.get_feature_names_out()))
print(set(vec_tf.get_feature_names_out())- set(vec_abs.get_feature_names_out()))

set()
set()


In [232]:
#check the difference between the feature names of relative frequency and tf-idf
print(set(vec_rel.get_feature_names_out())- set(vec_tf.get_feature_names_out()))
print(set(vec_tf.get_feature_names_out())- set(vec_rel.get_feature_names_out()))

set()
set()


There is no difference of the left features among the 3 approaches.

`max_df` is used for removing terms that appear too frequently, also known as "corpus-specific stop words". For example: 


*   `max_df` = 0.50 means "ignore terms that appear in more than 50% of the documents".

Another way around for `min_df`



In [233]:
#apply Binarizer()
binar = Binarizer()
vec_bi = binar.fit_transform(corpus_abs)
print(vec_bi.todense())

[[0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Meaning: if result returns 1, the word was count, if 0 was not count
Cons: only says if the word was count or not..

c. Put the frequencies for the first document from a. and b. in a data frame with a column keys containing the feature names from a. and four additional columns with the corresponding frequencies from a. and b. (Hint: Convert the corpus to an array first.). Keep only those rows of the data frame with keys representing words that exist in the first document.


In [234]:
data_0 = pd.DataFrame(vec_abs.get_feature_names_out(),columns = ['word'])
data_0['absolute'] = corpus_abs.toarray()[0]
data_0['relative'] = corpus_rel.toarray()[0]
data_0['tf'] = corpus_tf.toarray()[0]
data_0['binar'] = vec_bi.toarray()[0]

In [235]:
#choose words which are only in the first docu:
data_0 = data_0[data_0['absolute']!=0]

d. Sort the data frame (descending) on:
i. TF-IDF Frequencies
ii. Absolute Frequencies
Do you see differences? Why?

In [236]:
#tf-idf
data_0.sort_values("tf", ascending=False).head()

word  absolute  relative        tf  binar
30     car         5  0.294118  0.850894      1
128   look         2  0.117647  0.236711      1
197  small         1  0.058824  0.176815      1
105   info         1  0.058824  0.173306      1
63   engin         1  0.058824  0.171285      1

In [237]:
#absolute
data_0.sort_values("absolute", ascending=False).head()

word  absolute  relative        tf  binar
30     car         5  0.294118  0.850894      1
128   look         2  0.117647  0.236711      1
29    call         1  0.058824  0.149034      1
51     dai         1  0.058824  0.140068      1
63   engin         1  0.058824  0.171285      1

**Bag-of-words (gensim)**

---



In [238]:
#Create a corpus as input for gensim with corpus_gen=[doc.split() for doc in data_stem]. 
#What is this command exactly doing?
corpus_gen=[doc.split() for doc in data_stemmed]


In [239]:
id2word = Dictionary(corpus_gen)
id2word.filter_extremes(no_below=566, no_above=0.95)

In [240]:
print(id2word.token2id) #print out the key index and token which was filtered out
# less than 599 and more than 95% the total corpus size)

{'call': 0, 'car': 1, 'dai': 2, 'engin': 3, 'info': 4, 'know': 5, 'look': 6, 'mail': 7, 'small': 8, 'thank': 9, 'wonder': 10, 'year': 11, 'answer': 12, 'base': 13, 'card': 14, 'edu': 15, 'experi': 16, 'final': 17, 'gui': 18, 'host': 19, 'messag': 20, 'nntp': 21, 'number': 22, 'post': 23, 'report': 24, 'send': 25, 'access': 26, 'actual': 27, 'advanc': 28, 'anybodi': 29, 'better': 30, 'bit': 31, 'email': 32, 'expect': 33, 'feel': 34, 'good': 35, 'got': 36, 'great': 37, 'heard': 38, 'help': 39, 'life': 40, 'like': 41, 'line': 42, 'machin': 43, 'mayb': 44, 'new': 45, 'opinion': 46, 'peopl': 47, 'plai': 48, 'price': 49, 'probabl': 50, 'question': 51, 'read': 52, 'real': 53, 'recent': 54, 'start': 55, 'take': 56, 'time': 57, 'us': 58, 'wai': 59, 'address': 60, 'articl': 61, 'chip': 62, 'com': 63, 'far': 64, 'inform': 65, 'person': 66, 'phone': 67, 'point': 68, 'pretti': 69, 'requir': 70, 'stuff': 71, 'system': 72, 'thing': 73, 'write': 74, 'wrote': 75, 'check': 76, 'mean': 77, 'possibl': 78,

In [241]:
print(id2word.token2id.keys()) #print out all the tokens in array

dict_keys(['call', 'car', 'dai', 'engin', 'info', 'know', 'look', 'mail', 'small', 'thank', 'wonder', 'year', 'answer', 'base', 'card', 'edu', 'experi', 'final', 'gui', 'host', 'messag', 'nntp', 'number', 'post', 'report', 'send', 'access', 'actual', 'advanc', 'anybodi', 'better', 'bit', 'email', 'expect', 'feel', 'good', 'got', 'great', 'heard', 'help', 'life', 'like', 'line', 'machin', 'mayb', 'new', 'opinion', 'peopl', 'plai', 'price', 'probabl', 'question', 'read', 'real', 'recent', 'start', 'take', 'time', 'us', 'wai', 'address', 'articl', 'chip', 'com', 'far', 'inform', 'person', 'phone', 'point', 'pretti', 'requir', 'stuff', 'system', 'thing', 'write', 'wrote', 'check', 'mean', 'possibl', 'right', 'set', 'softwar', 'tell', 'understand', 'world', 'ye', 'agre', 'allow', 'apr', 'believ', 'come', 'consid', 'control', 'cost', 'cours', 'exist', 'follow', 'given', 'govern', 'hand', 'hard', 'hope', 'idea', 'john', 'kill', 'make', 'need', 'non', 'power', 'reason', 'result', 'sai', 'secon

In [242]:
print(id2word.dfs) #how many documents contain these tokens

{1: 700, 10: 702, 2: 1367, 6: 2215, 0: 1120, 8: 604, 5: 3532, 3: 683, 11: 2058, 4: 653, 7: 1394, 9: 2038, 17: 577, 24: 605, 21: 2335, 23: 3771, 19: 2423, 15: 6270, 22: 1182, 16: 629, 25: 743, 20: 823, 14: 705, 13: 899, 12: 768, 18: 596, 51: 1776, 55: 1234, 40: 750, 59: 2223, 45: 2950, 43: 611, 31: 1008, 44: 809, 29: 568, 33: 582, 38: 728, 26: 640, 49: 617, 42: 997, 41: 3863, 54: 632, 50: 1118, 36: 1223, 34: 710, 30: 1218, 37: 969, 35: 2341, 46: 1074, 47: 2554, 58: 2528, 56: 639, 53: 936, 48: 773, 27: 1099, 39: 1629, 28: 651, 32: 777, 52: 1497, 57: 2835, 63: 3925, 75: 810, 74: 6085, 61: 4995, 62: 581, 64: 961, 71: 574, 69: 654, 70: 735, 68: 1572, 60: 639, 67: 717, 65: 1113, 72: 607, 73: 2074, 66: 1249, 84: 1026, 85: 777, 77: 1487, 83: 733, 81: 829, 76: 652, 79: 1861, 80: 999, 78: 1208, 82: 1214, 112: 871, 102: 958, 88: 2845, 103: 768, 108: 967, 105: 1110, 93: 589, 106: 2188, 92: 930, 98: 848, 110: 688, 107: 750, 95: 831, 113: 1361, 90: 1674, 89: 1436, 100: 855, 114: 970, 86: 662, 99: 78

In [243]:
corpus1=[id2word.doc2bow(doc) for doc in corpus_gen] #Convert document into the bag-of-words (BoW) format = list of (token_id, token_count) tuples.

In [244]:
corpus2=[[(token[0],(token[1]/sum(n for _, n in doc))) for token in doc]
for doc in corpus1]
# Convert document into the bag-of-words (BoW) format = list of (token_id, token_count) tuple
#relative frequency

In [245]:
corpus3=[[(token[0],1) for token in doc] for doc in corpus1]
#One Hot encoding

In [246]:
tfidf=TfidfModel(dictionary=id2word, normalize=True) #implement Tfidf
corpus4=[tfidf[id2word.doc2bow(doc)] for doc in corpus_gen]

In [247]:
data_gensim = pd.DataFrame.from_dict(id2word.token2id,orient="index").reset_index()
data_gensim.columns = ['word','index']
#data_gensim.drop(['index'], axis=1)
#data_gensim['absolute'] = corpus_abs.toarray()[0]

In [248]:
df_1 = pd.DataFrame(corpus1[0], columns=['index','absolute'])
df_2 = pd.DataFrame(corpus2[0], columns=['index','relative'])
df_3 = pd.DataFrame(corpus3[0], columns=['index','OHE'])
df_4 = pd.DataFrame(corpus4[0], columns=['index','tf-idf'])

In [249]:
data_gensim = data_gensim.merge(df_1, how="left", left_on="index", right_index=True).drop(['index_y'], axis=1)
data_gensim = data_gensim.merge(df_2, how="left", left_on="index_x", right_index=True).drop(['index_x'], axis=1)
data_gensim = data_gensim.merge(df_3, how="left", left_on="index", right_index=True).drop(['index_y'], axis=1)
data_gensim = data_gensim.merge(df_4, how="left", left_on="index_x", right_index=True).drop(['index_x'], axis=1)
data_gensim.drop(['index'], axis=1)
data_gensim = data_gensim[data_gensim['absolute'].notna()]


In [251]:
data_gensim

word  absolute  relative  OHE  index    tf-idf
0     call       1.0  0.058824  1.0    0.0  0.143996
1      car       5.0  0.294118  1.0    1.0  0.866301
2      dai       1.0  0.058824  1.0    2.0  0.131588
3    engin       1.0  0.058824  1.0    3.0  0.174791
4     info       1.0  0.058824  1.0    4.0  0.177588
5     know       1.0  0.058824  1.0    5.0  0.072485
6     look       2.0  0.117647  1.0    6.0  0.203075
7     mail       1.0  0.058824  1.0    7.0  0.130370
8    small       1.0  0.058824  1.0    8.0  0.182444
9    thank       1.0  0.058824  1.0    9.0  0.106723
10  wonder       1.0  0.058824  1.0   10.0  0.173082
11    year       1.0  0.058824  1.0   11.0  0.106115

Here we observe that many words were filtered out with `no_below` and `no_above`

**N-Grams**

In [252]:
vec_ngram = CountVectorizer(ngram_range=(2, 2), max_df=0.95, min_df=0.05)
ngram = vec_ngram.fit_transform(data_stemmed)

In [255]:
ngram_df = pd.DataFrame(ngram.toarray(),columns=vec_ngram.get_feature_names_out())

In [256]:
ngram_df.head()

articl apr  edu write  nntp post  post host  write articl
0           0          0          0          0             0
1           0          0          1          1             0
2           0          0          0          0             0
3           0          1          1          1             1
4           0          0          0          0             0