<a href="https://colab.research.google.com/github/Heity94/TWSM_Lab/blob/main/Homework/3_Exercise_Representation_1/NL_3_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pickle
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import Binarizer
from gensim.corpora import Dictionary
from gensim.models import TfidfModel

In [7]:
with open ('/content/drive/MyDrive/Colab/data_stemmed.pkl','rb') as handle:
  data_stemmed = pickle.load(handle)

In [8]:
data_stemmed[0]

'car wonder enlighten car saw dai door sport car look late earli call bricklin door small addit bumper separ rest bodi know tellm model engin spec year product car histori info funki look car mail thank brought neighborhood lerxst'

In [9]:
#absolute frequency
vec_abs = CountVectorizer(max_df=0.95, min_df=0.05)
#relative frequency
vec_rel = TfidfVectorizer(max_df=0.95, min_df=0.05,use_idf=False, norm='l1')
#tf-idf frequency
vec_tf = TfidfVectorizer(max_df=0.95, min_df=0.05, smooth_idf=False)

Absolute frequency:


*   Pros: considers word importance, interpretable
*   Cons: not comparable between documents (i.e. long vs. short ones)

Relative frequency:


*   Pros: considers document length, interpretable
*   Cons: common words among all documents are overweighed (e.g. ‘annual’
in annual reports)

TF-idf:


*   Pros: Considers the occurrence among all documents (important for classification)
*   Cons: Difficult interpretation






In [10]:
#transform
corpus_abs = vec_abs.fit_transform(data_stemmed)
corpus_rel = vec_rel.fit_transform(data_stemmed)
corpus_tf = vec_tf.fit_transform(data_stemmed)
print("Absolute frequency: \n",corpus_abs.toarray()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
print("\n")
print("Relative frequency: \n", corpus_rel.toarray())
print("\n")
print("Tf-idf: \n", corpus_tf.toarray())

Absolute frequency: 
 [[0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Relative frequency: 
 [[0.         0.         0.         ... 0.         0.         0.05882353]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.01666667 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


Tf-idf: 
 [[0.         0.         0.         ... 0.         0.         0.12166272]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.11514646 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.    

In [11]:
corpus_abs.toarray().shape

(11314, 246)

In [12]:
#get feature names of tf-idf
print(len(vec_tf.get_feature_names_out()))
print((vec_tf.get_feature_names_out()))

246
['abl' 'accept' 'access' 'actual' 'address' 'advanc' 'ago' 'agre' 'allow'
 'american' 'answer' 'anybodi' 'appreci' 'apr' 'area' 'articl' 'ask'
 'assum' 'avail' 'awai' 'bad' 'base' 'believ' 'best' 'better' 'big' 'bit'
 'book' 'bui' 'call' 'car' 'card' 'care' 'case' 'caus' 'chang' 'check'
 'chip' 'christian' 'claim' 'close' 'com' 'come' 'complet' 'consid'
 'control' 'correct' 'cost' 'cours' 'creat' 'current' 'dai' 'data' 'david'
 'deal' 'design' 'differ' 'discuss' 'drive' 'edu' 'effect' 'email' 'end'
 'engin' 'exampl' 'exist' 'expect' 'experi' 'fact' 'far' 'fax' 'feel'
 'file' 'final' 'follow' 'forc' 'free' 'friend' 'game' 'gener' 'get'
 'given' 'go' 'god' 'good' 'got' 'govern' 'great' 'group' 'guess' 'gui'
 'hand' 'happen' 'hard' 'have' 'heard' 'help' 'high' 'home' 'hope' 'host'
 'human' 'idea' 'import' 'includ' 'info' 'inform' 'interest' 'internet'
 'isn' 'issu' 'john' 'kei' 'kill' 'kind' 'know' 'larg' 'law' 'left' 'let'
 'life' 'like' 'line' 'list' 'littl' 'live' 'local' 'long' 'l

In [13]:
#get feature names of accurate and relative frequency
print(len(vec_abs.get_feature_names_out()))
print(len(vec_rel.get_feature_names_out()))

246
246


In [14]:
#check the difference between the feature names of absolute frequency and tf-idf
print(set(vec_abs.get_feature_names_out())- set(vec_tf.get_feature_names_out()))
print(set(vec_tf.get_feature_names_out())- set(vec_abs.get_feature_names_out()))

set()
set()


In [15]:
#check the difference between the feature names of relative frequency and tf-idf
print(set(vec_rel.get_feature_names_out())- set(vec_tf.get_feature_names_out()))
print(set(vec_tf.get_feature_names_out())- set(vec_rel.get_feature_names_out()))

set()
set()


There is no difference of the left features among the 3 approaches.

`max_df` is used for removing terms that appear too frequently, also known as "corpus-specific stop words". For example: 


*   `max_df` = 0.50 means "ignore terms that appear in more than 50% of the documents".

Another way around for `min_df`



In [16]:
#apply Binarizer()
binar = Binarizer()
vec_bi = binar.fit_transform(corpus_abs)
print(vec_bi.todense())

[[0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Meaning: if result returns 1, the word was count, if 0 was not count
Cons: only says if the word was count or not..

c. Put the frequencies for the first document from a. and b. in a data frame with a column keys containing the feature names from a. and four additional columns with the corresponding frequencies from a. and b. (Hint: Convert the corpus to an array first.). Keep only those rows of the data frame with keys representing words that exist in the first document.


In [17]:
data_0 = pd.DataFrame(vec_abs.get_feature_names_out(),columns = ['word'])
data_0['absolute'] = corpus_abs.toarray()[0]
data_0['relative'] = corpus_rel.toarray()[0]
data_0['tf'] = corpus_tf.toarray()[0]
data_0['binar'] = vec_bi.toarray()[0]

In [18]:
#choose words which are only in the first docu:
data_0 = data_0[data_0['absolute']!=0]

d. Sort the data frame (descending) on:
i. TF-IDF Frequencies
ii. Absolute Frequencies
Do you see differences? Why?

In [20]:
#tf-idf
data_0.sort_values("tf", ascending=False).head()

word  absolute  relative        tf  binar
30     car         5  0.294118  0.850894      1
128   look         2  0.117647  0.236711      1
197  small         1  0.058824  0.176815      1
105   info         1  0.058824  0.173306      1
63   engin         1  0.058824  0.171285      1

In [21]:
#absolute
data_0.sort_values("absolute", ascending=False).head()

word  absolute  relative        tf  binar
30     car         5  0.294118  0.850894      1
128   look         2  0.117647  0.236711      1
29    call         1  0.058824  0.149034      1
51     dai         1  0.058824  0.140068      1
63   engin         1  0.058824  0.171285      1

There is no difference here.